# .github/workflows/test.yml
name: Test Nestor
on:
  push:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: make install
      - name: Run Hub tests
        run: make testhub
      - name: Run Service tests
        run: make testservice
      - name: Run Client tests
        run: make testclient
